"""Constantes do domínio — etapas padrão e mapeamento de riscos por keywords."""

ETAPAS_PADRAO = [
    "Planejamento e Projeto",
    "Preparacao do Terreno",
    "Fundacoes e Estrutura",
    "Alvenaria e Cobertura",
    "Instalacoes e Acabamentos",
    "Entrega e Pos-obra",
]

RISCO_ETAPA_KEYWORDS: dict[str, list[str]] = {
    "fundação": ["Fundacoes e Estrutura"],
    "fundacao": ["Fundacoes e Estrutura"],
    "estrutura": ["Fundacoes e Estrutura"],
    "concreto": ["Fundacoes e Estrutura"],
    "ferragem": ["Fundacoes e Estrutura"],
    "armadura": ["Fundacoes e Estrutura"],
    "estaca": ["Fundacoes e Estrutura"],
    "sapata": ["Fundacoes e Estrutura"],
    "terreno": ["Preparacao do Terreno"],
    "terraplanagem": ["Preparacao do Terreno"],
    "topografia": ["Preparacao do Terreno"],
    "sondagem": ["Preparacao do Terreno"],
    "demolição": ["Preparacao do Terreno"],
    "demolicao": ["Preparacao do Terreno"],
    "alvenaria": ["Alvenaria e Cobertura"],
    "cobertura": ["Alvenaria e Cobertura"],
    "telhado": ["Alvenaria e Cobertura"],
    "laje": ["Alvenaria e Cobertura"],
    "impermeabilização": ["Alvenaria e Cobertura"],
    "impermeabilizacao": ["Alvenaria e Cobertura"],
    "elétric": ["Instalacoes e Acabamentos"],
    "eletric": ["Instalacoes e Acabamentos"],
    "hidráulic": ["Instalacoes e Acabamentos"],
    "hidraulic": ["Instalacoes e Acabamentos"],
    "acabamento": ["Instalacoes e Acabamentos"],
    "revestimento": ["Instalacoes e Acabamentos"],
    "pintura": ["Instalacoes e Acabamentos"],
    "piso": ["Instalacoes e Acabamentos"],
    "entrega": ["Entrega e Pos-obra"],
    "habite-se": ["Entrega e Pos-obra"],
    "vistoria": ["Entrega e Pos-obra"],
    "garantia": ["Entrega e Pos-obra"],
    "projeto": ["Planejamento e Projeto"],
    "licença": ["Planejamento e Projeto"],
    "licenca": ["Planejamento e Projeto"],
    "alvará": ["Planejamento e Projeto"],
    "alvara": ["Planejamento e Projeto"],
}
